---
dependency:
  name: galaxy
driver:
  name: docker
  options:
    D: true
    vv: true
platforms:
  - name: centos8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
  options:
    D: true
    vv: true
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
verifier:
  name: ansible
...
